services:
  postgres-dena:
    image: postgres:16
    container_name: postgres-dena
    restart: unless-stopped
    environment:
      POSTGRES_DB: dena
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"
    volumes:
      - postgres_dena_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-keycloak:
    image: postgres:16
    container_name: postgres-keycloak
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak
    restart: unless-stopped
    command: start
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password

      #KC_HTTP_MANAGEMENT_PORT: 9090

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin_password

      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
    ports:
      - "9090:8080"
    depends_on:
      - postgres-keycloak
    networks:
      - keycloak-network

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: dena-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./src/main/resources/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

volumes:
  postgres_dena_data:
  postgres_keycloak_data:
  prometheus-data:

networks:
  keycloak-network: