logging:
  level:
    root: INFO
    de.bund.bva.isyfact: INFO
    org.example: INFO
    org.hibernate.stat: DEBUG
    org.hibernate.cache: DEBUG
    org.hibernate.SQL: DEBUG


# it was required for IsyFact logging lib
isy:
  logging:
    anwendung:
      name: DenaApp
      typ: backend
      version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: dena-app
  prometheus:
    metrics:
      export:
        enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dena
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      org.hibernate.envers.global_with_modified_flag: true
      hibernate:
        envers:
          autoRegisterListeners: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          javax:
            cache:
              provider: org.ehcache.jsr107.EhcacheCachingProvider
          cache:
            region:
              factory_class: jcache
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/dena-realm
          jwk-set-uri: http://localhost:9090/realms/dena-realm/protocol/openid-connect/certs

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui


energy:
  threshold: 1000