package org.example.domain;

public enum UserActionType {
    ADMINISTRATION_UNIT_CREATED,
    ADMINISTRATION_UNIT_UPDATED,
    ADMINISTRATION_UNIT_ATTRIBUTE_CREATED,
    ADMINISTRATION_UNIT_ATTRIBUTE_DELETED,
    ENERGY_READING_SUBMITTED,
    ENERGY_CSV_IMPORTED
}
