--liquibase formatted sql

--changeset vitalii:005-create-user-action-log

CREATE TABLE user_action_log
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at    TIMESTAMPTZ  NOT NULL,
    actor_id       VARCHAR(255) NOT NULL,
    actor_name     VARCHAR(255),
    action         VARCHAR(100) NOT NULL,
    outcome        VARCHAR(16)  NOT NULL,
    target_type    VARCHAR(100) NOT NULL,
    target_id      VARCHAR(255),
    request_id     VARCHAR(64),
    http_method    VARCHAR(10),
    request_path   VARCHAR(2048),
    remote_address VARCHAR(45),
    user_agent     VARCHAR(512),
    metadata       JSONB        NOT NULL DEFAULT '{}'::jsonb,

    CONSTRAINT chk_user_action_log_outcome
        CHECK (outcome IN ('SUCCESS', 'FAILURE', 'DENIED'))
);

--rollback DROP TABLE user_action_log;

--changeset vitalii:005-create-user-action-log-indexes
CREATE INDEX idx_user_action_log_actor_id ON user_action_log(actor_id);
CREATE INDEX idx_user_action_log_action ON user_action_log(action);
CREATE INDEX idx_user_action_log_occurred_at ON user_action_log(occurred_at);
CREATE INDEX idx_user_action_log_target_type ON user_action_log(target_type);
CREATE INDEX idx_user_action_log_target_id ON user_action_log(target_id);
CREATE INDEX idx_user_action_log_request_id ON user_action_log(request_id);