--liquibase formatted sql

--changeset vitalii:006-create-revinfo-table
--comment: Hibernate Envers revision table (CustomRevisionEntity)
CREATE TABLE revinfo
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY,
    timestamp      BIGINT NOT NULL,
    username       VARCHAR(255),
    application    VARCHAR(255),
    remote_address VARCHAR(45),
    request_id     VARCHAR(64),

    CONSTRAINT pk_revinfo PRIMARY KEY (id)
);

--rollback DROP TABLE revinfo;
